### ISSUE TITLE
Authentication failed for https://maven.pkg.github.com/equinor/fiberoptics-das-public-schemas

### ISSUE THREAD

**Issue by hasanari** [equinor/fiberoptics-das-simulator#4]
Hi  @espentj @oyron @hansrune @MatsGA @ingvald ,

I currently work on a DAS project with Equinor (DIFI-PRO project).
This repo really interests me. Is your maven packages closed for public access?

I try to run the code, but it seems the dependencies require authentication.

Hasan

**Comment by espentj** [comment]
Hi Hasan, unfortunately Github packages does not allow anonymous access to packages yet (that is needed for maven package access publically). 
So there are two alternatives to get this working.

1. Download and run ./mvnw install on https://github.com/equinor/fiberoptics-das-public-schemas -> will add the artifact in your local cache
2. Add a section into your private .m2/settings.xml that has the id 'github' and add a PAT token : https://github.com/settings/tokens that has read:packages access associated with your github username
